### ISSUE TITLE
>trying not to be bloat\n >using github instead of gitlab or something selfhosted\n meh

### ISSUE THREAD

**Issue by sophronesis** [metis-os/metis-iso#1]
https://lunduke.substack.com/p/watch-as-the-microsoft-open-source
Hope you know what to do next

**Comment by whoisYoges** [comment]
Yep! It's been drawing our attention too! We'll soon be available on gitlab too. You could recommend us if there's any other better (or the best) alternative? We'd have a look and may switch too it.
